In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("leads_seed.csv")
df

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,City,...,Original Source,Original Source Drill-Down 1,Contact Owner,Create Date,Last Modified Date,Notes,Annual Revenue,Marketing contact status,GDPR consent,Lead Score
0,100234811,Yuki,Aina,NaN,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,China,NaN,...,NaN,NaN,Marcus Wong,12/21/2025,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN,NaN,NaN,NaN
1,100234812,Wei Ming,Malik,NaN,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,France,NaN,...,Referrals,NaN,Rohan Mehta,1/29/2026,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN,NaN,NaN,NaN
2,100234813,Linh,Lim,NaN,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,Poland,NaN,...,NaN,NaN,Grace Osei,2025-09-29,10/15/2025,Filled out the form on the contact page.,NaN,NaN,NaN,NaN
3,100234814,Ines,Wu,NaN,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,Portugal,NaN,...,Direct Traffic,NaN,Priya Nair,2025-10-27T00:00:00Z,2025-12-06,Filled out the form on the contact page. Very ...,NaN,NaN,NaN,NaN
4,100234815,Xiu Ying,Martinez,NaN,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,France,NaN,...,Paid Search,NaN,Diego Alvarez,2026-05-18,5/27/2026,Booked a demo via the book-a-demo page after c...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2044,100236855,Karim,Yap,NaN,VP Sales,Orchid Holdings,karim.y@orchid.com,+49 168 6700339,Germany,NaN,...,Social Media,NaN,Diego Alvarez,2026-01-23T00:00:00Z,3/7/2026,Saw our post about replacing hubspot and comme...,NaN,NaN,NaN,NaN
2045,100236856,Karim,Yap,NaN,VP Sales,Orchid Ltd,karimyap@orchid.com,491686700339,Germany,NaN,...,Social Media,NaN,Diego Alvarez,2026-01-23,3/7/2026,Saw our post about replacing hubspot and comme...,NaN,NaN,NaN,NaN
2046,100236857,Musa,Seo,NaN,Finance Manager,Patel Fintech Ventures,m.seo@patelfintech.com,+234 801 853 6245,Nigeria,NaN,...,Social Media,NaN,Diego Alvarez,2025-10-10T00:00:00Z,2025-10-10,Connected on LinkedIn after commenting on our ...,NaN,NaN,NaN,NaN
2047,100236858,Musa,Seo,NaN,Finance Manager,Patel Fintech Holdings,musaseo@patelfintech.com,2348018536245,Nigeria,NaN,...,Social Media,NaN,Diego Alvarez,10/10/2025,2025-10-10,Connected on LinkedIn after commenting on our ...,NaN,NaN,NaN,NaN
2048,100236859,Valentina,Lim,NaN,NaN,Yang Freight Studio,valentina.lim@yangfreight.com,+84 92 952 2654,Vietnam,NaN,...,Paid Search,NaN,Grace Osei,2025-11-01,3/22/2026,Booked a demo via the book-a-demo page after c...,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2049 entries, 0 to 2048
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Record ID                     2049 non-null   int64
 1   First Name                    1942 non-null   object
 2   Last Name                     1942 non-null   object
 3   Full Name                     107 non-null    object
 4   Job Title                     1221 non-null   object
 5   Company Name                  2049 non-null   object
 6   Email                         2049 non-null   object
 7   Phone Number                  2049 non-null   object
 8   Country/Region                2049 non-null   object
 9   City                          0 non-null      float64
 10  Lead Status                   2049 non-null   object
 11  Lifecycle Stage               1756 non-null   object
 12  Original Source               1035 non-null   object
 13  Original Source Drill-Down 1  0 non-null      float64
 14  Contact Owner                 2049 non-null   object
 15  Create Date                   2049 non-null   object
 16  Last Modified Date            1496 non-null   object
 17  Notes                         2049 non-null   object
 18  Annual Revenue                0 non-null      float64
 19  Marketing contact status      0 non-null      float64
 20  GDPR consent                  0 non-null      float64
 21  Lead Score                    153 non-null    float64
dtypes: float64(6), int64(1), object(15)
memory usage: 352.3+ KB

In [4]:
df = df.dropna(how='all', axis=1)
df

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,Lead Status,Lifecycle Stage,Original Source,Contact Owner,Create Date,Last Modified Date,Notes,Lead Score
0,100234811,Yuki,Aina,NaN,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,China,New,Lead,NaN,Marcus Wong,12/21/2025,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN
1,100234812,Wei Ming,Malik,NaN,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,France,Qualified,Lead,Referrals,Rohan Mehta,1/29/2026,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN
2,100234813,Linh,Lim,NaN,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,Poland,Opportunity,Marketing Qualified Lead,NaN,Grace Osei,2025-09-29,10/15/2025,Filled out the form on the contact page.,NaN
3,100234814,Ines,Wu,NaN,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,Portugal,qualified,Lead,Direct Traffic,Priya Nair,2025-10-27T00:00:00Z,2025-12-06,Filled out the form on the contact page. Very ...,NaN
4,100234815,Xiu Ying,Martinez,NaN,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,France,Closed Won,Other,Paid Search,Diego Alvarez,2026-05-18,5/27/2026,Booked a demo via the book-a-demo page after c...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2044,100236855,Karim,Yap,NaN,VP Sales,Orchid Holdings,karim.y@orchid.com,+49 168 6700339,Germany,NEW,NaN,Social Media,Diego Alvarez,2026-01-23T00:00:00Z,3/7/2026,Saw our post about replacing hubspot and comme...,NaN
2045,100236856,Karim,Yap,NaN,VP Sales,Orchid Ltd,karimyap@orchid.com,491686700339,Germany,New,NaN,Social Media,Diego Alvarez,2026-01-23,3/7/2026,Saw our post about replacing hubspot and comme...,NaN
2046,100236857,Musa,Seo,NaN,Finance Manager,Patel Fintech Ventures,m.seo@patelfintech.com,+234 801 853 6245,Nigeria,Qualified,Other,Social Media,Diego Alvarez,2025-10-10T00:00:00Z,2025-10-10,Connected on LinkedIn after commenting on our ...,NaN
2047,100236858,Musa,Seo,NaN,Finance Manager,Patel Fintech Holdings,musaseo@patelfintech.com,2348018536245,Nigeria,qualified,Other,Social Media,Diego Alvarez,10/10/2025,2025-10-10,Connected on LinkedIn after commenting on our ...,NaN
2048,100236859,Valentina,Lim,NaN,NaN,Yang Freight Studio,valentina.lim@yangfreight.com,+84 92 952 2654,Vietnam,CONNECTED,Customer,Paid Search,Grace Osei,2025-11-01,3/22/2026,Booked a demo via the book-a-demo page after c...,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2049 entries, 0 to 2048
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Record ID           2049 non-null   int64
 1   First Name          1942 non-null   object
 2   Last Name           1942 non-null   object
 3   Full Name           107 non-null    object
 4   Job Title           1221 non-null   object
 5   Company Name        2049 non-null   object
 6   Email               2049 non-null   object
 7   Phone Number        2049 non-null   object
 8   Country/Region      2049 non-null   object
 9   Lead Status         2049 non-null   object
 10  Lifecycle Stage     1756 non-null   object
 11  Original Source     1035 non-null   object
 12  Contact Owner       2049 non-null   object
 13  Create Date         2049 non-null   object
 14  Last Modified Date  1496 non-null   object
 15  Notes               2049 non-null   object
 16  Lead Score          153 non-null    float64
dtypes: float64(1), int64(1), object(15)
memory usage: 272.3+ KB

In [6]:
df['Job Title'].value_counts()

Job Title
Operations Lead       223
Marketing Director    214
VP Sales              211
Head of Growth        203
Founder               193
Finance Manager       177
Name: count, dtype: int64

In [7]:
df['Lead Status'].value_counts()

Lead Status
Closed Lost     198
Qualified       181
Connected       160
Contacted       159
Opportunity     155
New             151
Closed Won      151
opportunity      56
closed lost      54
new              51
CLOSED WON       51
qualified        48
connected        47
contacted        45
QUALIFIED        43
CONTACTED        42
closed won       39
NEW              39
OPPORTUNITY      39
CONNECTED        32
CLOSED LOST      31
Connected        27
 Connected       27
 Qualified       25
Qualified        24
Opportunity      22
 Closed Lost     19
 Opportunity     19
 Contacted       19
Closed Won       18
 Closed Won      17
Contacted        17
 New             17
Closed Lost      14
New              12
Name: count, dtype: int64

In [8]:
df['Lead Status'].unique()

array(['New', 'Qualified ', 'Opportunity', 'qualified', 'Closed Won',
       'CONNECTED', 'CLOSED LOST', 'Contacted', ' Opportunity',
       'closed won', 'Connected', 'Qualified', 'Closed Lost', 'connected',
       'opportunity', 'New ', 'Closed Lost ', 'Contacted ', 'Connected ',
       'Opportunity ', 'new', 'CLOSED WON', 'contacted', 'closed lost',
       ' Connected', ' Qualified', 'QUALIFIED', ' Contacted', ' New',
       'OPPORTUNITY', 'Closed Won ', ' Closed Won', 'NEW', ' Closed Lost',
       'CONTACTED'], dtype=object)

In [9]:
df['Lead Status'] = df['Lead Status'].str.lower()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_30552\2142941521.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Lead Status'] = df['Lead Status'].str.lower()

In [10]:
df['Lead Status'].unique()

array(['new', 'qualified ', 'opportunity', 'qualified', 'closed won',
       'connected', 'closed lost', 'contacted', ' opportunity', 'new ',
       'closed lost ', 'contacted ', 'connected ', 'opportunity ',
       ' connected', ' qualified', ' contacted', ' new', 'closed won ',
       ' closed won', ' closed lost'], dtype=object)

In [11]:
df['Lead Status'] = df['Lead Status'].str.strip()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_30552\2043246041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Lead Status'] = df['Lead Status'].str.strip()

In [12]:
df['Lead Status'].unique()

array(['new', 'qualified', 'opportunity', 'closed won', 'connected',
       'closed lost', 'contacted'], dtype=object)

In [13]:
df['Contact Owner'].value_counts()

Contact Owner
Elena Popescu      249
Hana Kobayashi     215
Grace Osei         215
Priya Nair         201
Fatima Rahman      194
Marcus Wong        191
Noah Bennett       191
Wei Chen           181
Diego Alvarez      179
Rohan Mehta        167
Hana Kobayashi      10
Priya Nair           9
Marcus Wong          9
Rohan Mehta          8
Noah Bennett         7
Wei Chen             6
Grace Osei           6
Diego Alvarez        4
Fatima Rahman        4
Elena Popescu        3
Name: count, dtype: int64

In [14]:
df['Contact Owner'].unique()

array(['Marcus Wong ', 'Rohan Mehta', 'Grace Osei', 'Priya Nair',
       'Diego Alvarez', 'Elena Popescu', 'Fatima Rahman', 'Wei Chen',
       'Marcus Wong', 'Noah Bennett', 'Hana Kobayashi', 'Hana Kobayashi ',
       'Wei Chen ', 'Noah Bennett ', 'Priya Nair ', 'Grace Osei ',
       'Rohan Mehta ', 'Elena Popescu ', 'Diego Alvarez ',
       'Fatima Rahman '], dtype=object)

In [15]:
df['Contact Owner'] = df['Contact Owner'].str.strip()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_30552\1718446573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Contact Owner'] = df['Contact Owner'].str.strip()

In [16]:
df['Contact Owner'].unique()

array(['Marcus Wong', 'Rohan Mehta', 'Grace Osei', 'Priya Nair',
       'Diego Alvarez', 'Elena Popescu', 'Fatima Rahman', 'Wei Chen',
       'Noah Bennett', 'Hana Kobayashi'], dtype=object)

In [17]:
df['Country/Region'].value_counts()

Country/Region
United Kingdom    79
Netherlands       79
Australia         70
India             70
Denmark           69
                  ..
india              1
brazil             1
indonesia          1
singapore          1
vietnam            1
Name: count, Length: 62, dtype: int64

In [18]:
df['Country/Region'].unique()

array(['China', 'France', 'Poland', 'Portugal', 'South Korea',
       'Indonesia', 'United Kingdom', 'Netherlands', 'Thailand', 'Sweden',
       'Singapore', 'Greece', 'Philippines', 'Romania', 'Vietnam',
       'India', 'Nigeria', 'Germany', 'Japan', 'italy', 'United States',
       'Bangladesh', 'UAE', 'Pakistan', 'Morocco', 'Malaysia', 'Ghana',
       'Russia', 'Mexico', 'Hong Kong', 'Denmark', 'Australia', 'Spain',
       'Brazil', 'Argentina', 'germany', 'Italy', 'poland', 'philippines',
       'spain', 'india', 'indonesia', 'united kingdom', 'pakistan',
       'bangladesh', 'china', 'australia', 'singapore', 'hong kong',
       'france', 'brazil', 'malaysia', 'netherlands', 'romania', 'greece',
       'nigeria', 'sweden', 'denmark', 'thailand', 'united states',
       'portugal', 'vietnam'], dtype=object)

In [19]:
df['Country/Region'] = df['Country/Region'].str.lower()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_30552\110191067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country/Region'] = df['Country/Region'].str.lower()

In [20]:
df['Country/Region'].unique()

array(['china', 'france', 'poland', 'portugal', 'south korea',
       'indonesia', 'united kingdom', 'netherlands', 'thailand', 'sweden',
       'singapore', 'greece', 'philippines', 'romania', 'vietnam',
       'india', 'nigeria', 'germany', 'japan', 'italy', 'united states',
       'bangladesh', 'uae', 'pakistan', 'morocco', 'malaysia', 'ghana',
       'russia', 'mexico', 'hong kong', 'denmark', 'australia', 'spain',
       'brazil', 'argentina'], dtype=object)

In [21]:
df['Country/Region'].value_counts()

Country/Region
united kingdom    81
netherlands       81
australia         71
denmark           71
india             71
thailand          67
singapore         67
uae               67
philippines       66
poland            65
nigeria           64
spain             64
china             63
morocco           60
ghana             60
mexico            58
pakistan          57
indonesia         56
south korea       56
italy             56
united states     56
greece            56
germany           55
bangladesh        55
portugal          55
sweden            54
brazil            52
france            50
hong kong         50
russia            49
malaysia          48
vietnam           47
japan             44
romania           44
argentina         33
Name: count, dtype: int64

In [22]:
df['Full Name'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2049 entries, 0 to 2048
Series name: Full Name
Non-Null Count  Dtype
--------------  -----
107 non-null    object
dtypes: object(1)
memory usage: 16.1+ KB

In [23]:
df.iloc[0:25]

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,Lead Status,Lifecycle Stage,Original Source,Contact Owner,Create Date,Last Modified Date,Notes,Lead Score
0,100234811,Yuki,Aina,NaN,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,china,new,Lead,NaN,Marcus Wong,12/21/2025,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN
1,100234812,Wei Ming,Malik,NaN,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,france,qualified,Lead,Referrals,Rohan Mehta,1/29/2026,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN
2,100234813,Linh,Lim,NaN,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,poland,opportunity,Marketing Qualified Lead,NaN,Grace Osei,2025-09-29,10/15/2025,Filled out the form on the contact page.,NaN
3,100234814,Ines,Wu,NaN,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,portugal,qualified,Lead,Direct Traffic,Priya Nair,2025-10-27T00:00:00Z,2025-12-06,Filled out the form on the contact page. Very ...,NaN
4,100234815,Xiu Ying,Martinez,NaN,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,france,closed won,Other,Paid Search,Diego Alvarez,2026-05-18,5/27/2026,Booked a demo via the book-a-demo page after c...,NaN
5,100234816,Natasha,Osei,NaN,Finance Manager,Singh Logistics Ltd,n.osei@singhlogistics.net,+82 10-8787-3705,south korea,connected,Customer,NaN,Elena Popescu,2026-04-05,2026-06-13,Filled out the form on the blog post on lead s...,NaN
6,100234817,Arjun,Oh,NaN,Founder,Mekong Pte. Ltd.,arjuno@mekong.net,+62 875-4899-5562,indonesia,closed lost,Opportunity,Other Campaigns,Fatima Rahman,2026-06-04,6/4/2026,Other - reached out via our general info@ inbo...,NaN
7,100234818,Omar,Reyes,NaN,VP Sales,Sayed Trading Holdings,omar.reyes@sayedtrading.net,+44 7798 299448,united kingdom,opportunity,Opportunity,Organic Search,Wei Chen,2026-04-05,2026-06-03,Googled us and ended up on the book-a-demo pag...,NaN
8,100234819,Abena,Lee,NaN,NaN,Lindqvist AB and Co,abena.l@lindqvistab.net,+31 6 7930 8973,netherlands,contacted,Marketing Qualified Lead,NaN,Diego Alvarez,2025-12-21T00:00:00Z,NaN,Manually added by sales after a phone call fro...,NaN
9,100234820,Nadia,Weber,NaN,NaN,Sato Labs,nadia.weber@sato.io,+66 9 9565 6183,thailand,connected,Marketing Qualified Lead,NaN,Grace Osei,2026-01-01,2026-02-03T00:00:00Z,Manual - added after inbound phone call. No re...,92.0
10,100234821,Marcus,Russo,NaN,Founder,Diallo Imports Freight Solutions,marcus.russo@dialloimports.co,+46 70 779 23 27,sweden,connected,Lead,NaN,Marcus Wong,6/11/2026,NaN,"Referred by Xiu Ying Choi, warm intro. Great f...",NaN
11,100234822,Aiko,Goh,NaN,NaN,Singh Logistics Partners,aiko.g@singhlogistics.biz,+65 8177 3442,singapore,opportunity,Lead,Offline Sources,Grace Osei,2026-06-10T00:00:00Z,6/10/2026,Scanned the QR code at our TechCrunch Disrupt ...,NaN
12,100234823,Wei Chen,Ang,NaN,NaN,Fischer Trading Pte Ltd,weichena@fischertrading.io,+30 694 373 3608,greece,closed won,Other,NaN,Marcus Wong,3/15/2026,2026-05-14,Googled us and ended up on the product tour pa...,44.0
13,100234824,Joon,Nguyen,NaN,Operations Lead,Sato and Co,joonn@sato.io,+63 923 710 8119,philippines,connected,Other,NaN,Grace Osei,2026-04-12,2026-06-16T00:00:00Z,"Met her at the Mobile World Congress booth, sc...",88.0
14,100234825,Fatima,Iyer,NaN,NaN,Sim Robotics Freight,fatimai@simrobotics.sg,+40 757 667 230,romania,contacted,Opportunity,NaN,Noah Bennett,2025-11-29,NaN,Connected on LinkedIn after commenting on our ...,NaN
15,100234826,Kai,Osei,NaN,Operations Lead,Tanaka Freight,kaio@tanaka.biz,+66 7 6085 4680,thailand,closed won,Marketing Qualified Lead,Other Campaigns,Wei Chen,2025-09-13,NaN,Other - walked into our office without an appo...,NaN
16,100234827,Hassan,Schulz,NaN,Founder,Osei Freight Solutions,hassan.s@osei.com.au,+84 98 355 2988,vietnam,qualified,Marketing Qualified Lead,NaN,Hana Kobayashi,5/30/2026,2026-06-18,Googled us and ended up on the product tour pa...,NaN
17,100234828,Nadia,Sun,NaN,Operations Lead,Bakker Partners,n.sun@bakker.com,+91 77577 60205,india,closed lost,Marketing Qualified Lead,Referrals,Fatima Rahman,10/3/2025,2026-03-21,"Referred by Ismail Reyes, warm intro. Very int...",NaN
18,100234829,Farah,Martins,NaN,Marketing Director,Verma Consulting Partners,f.martins@vermaconsulting.net,+234 804 379 8140,nigeria,qualified,Lead,NaN,Noah Bennett,2026-02-20,2026-06-02T00:00:00Z,Connected on LinkedIn after commenting on our ...,NaN
19,100234830,Ha-eun,Kang,NaN,NaN,Cruz & Partners Holdings,ha-eun.k@cruzpartners.net,+49 174 8072684,germany,connected,NaN,Social Media,Marcus Wong,2026-04-29,NaN,Linkedin dm inbound asking about pricing.,NaN
20,100234831,Lucas,Bruno,NaN,Marketing Director,Huang Analytics Robotics,l.bruno@huanganalytics.co,+81 75-6096-2771,japan,opportunity,Lead,Offline Sources,Diego Alvarez,2026-03-12,2026-06-11,"Met at the booth during Mobile World Congress,...",NaN
21,100234832,Farah,Bruno,NaN,NaN,Huang Analytics Robotics,farah.bruno@huanganalytics.co,+91 84270 33086,india,closed lost,Customer,NaN,Diego Alvarez,6/3/2026,2026-06-17,Saw our post about replacing hubspot and comme...,NaN
22,100234833,Antoine,Asante,NaN,Founder,Koh & Sons Co.,antoinea@kohsons.co,+39 357 710 5526,italy,opportunity,Lead,Other Campaigns,Rohan Mehta,2025-12-07,2025-12-07,Manual - added after inbound phone call. Not i...,NaN
23,100234834,Joon,Diallo,NaN,VP Sales,Huang Analytics and Co,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,6/7/2026,Spoke with them at our Dubai FinTech Week boot...,NaN
24,100234835,NaN,NaN,J. Diallo,VP Sales,Huang Analytics and Pte. Ltd.,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,2026-06-07,Spoke with them at our Dubai FinTech Week boot...,NaN

In [24]:
df['Full Name'] = np.where(
    df['First Name'].isna() & df['Last Name'].isna(),  
    df['Full Name'],                                    
    df['First Name'].fillna('') + ' ' + df['Last Name'].fillna('')  
)

C:\Users\Wilson\AppData\Local\Temp\ipykernel_30552\1149395654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Full Name'] = np.where(

In [25]:
df.iloc[0:25]

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,Lead Status,Lifecycle Stage,Original Source,Contact Owner,Create Date,Last Modified Date,Notes,Lead Score
0,100234811,Yuki,Aina,Yuki Aina,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,china,new,Lead,NaN,Marcus Wong,12/21/2025,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN
1,100234812,Wei Ming,Malik,Wei Ming Malik,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,france,qualified,Lead,Referrals,Rohan Mehta,1/29/2026,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN
2,100234813,Linh,Lim,Linh Lim,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,poland,opportunity,Marketing Qualified Lead,NaN,Grace Osei,2025-09-29,10/15/2025,Filled out the form on the contact page.,NaN
3,100234814,Ines,Wu,Ines Wu,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,portugal,qualified,Lead,Direct Traffic,Priya Nair,2025-10-27T00:00:00Z,2025-12-06,Filled out the form on the contact page. Very ...,NaN
4,100234815,Xiu Ying,Martinez,Xiu Ying Martinez,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,france,closed won,Other,Paid Search,Diego Alvarez,2026-05-18,5/27/2026,Booked a demo via the book-a-demo page after c...,NaN
5,100234816,Natasha,Osei,Natasha Osei,Finance Manager,Singh Logistics Ltd,n.osei@singhlogistics.net,+82 10-8787-3705,south korea,connected,Customer,NaN,Elena Popescu,2026-04-05,2026-06-13,Filled out the form on the blog post on lead s...,NaN
6,100234817,Arjun,Oh,Arjun Oh,Founder,Mekong Pte. Ltd.,arjuno@mekong.net,+62 875-4899-5562,indonesia,closed lost,Opportunity,Other Campaigns,Fatima Rahman,2026-06-04,6/4/2026,Other - reached out via our general info@ inbo...,NaN
7,100234818,Omar,Reyes,Omar Reyes,VP Sales,Sayed Trading Holdings,omar.reyes@sayedtrading.net,+44 7798 299448,united kingdom,opportunity,Opportunity,Organic Search,Wei Chen,2026-04-05,2026-06-03,Googled us and ended up on the book-a-demo pag...,NaN
8,100234819,Abena,Lee,Abena Lee,NaN,Lindqvist AB and Co,abena.l@lindqvistab.net,+31 6 7930 8973,netherlands,contacted,Marketing Qualified Lead,NaN,Diego Alvarez,2025-12-21T00:00:00Z,NaN,Manually added by sales after a phone call fro...,NaN
9,100234820,Nadia,Weber,Nadia Weber,NaN,Sato Labs,nadia.weber@sato.io,+66 9 9565 6183,thailand,connected,Marketing Qualified Lead,NaN,Grace Osei,2026-01-01,2026-02-03T00:00:00Z,Manual - added after inbound phone call. No re...,92.0
10,100234821,Marcus,Russo,Marcus Russo,Founder,Diallo Imports Freight Solutions,marcus.russo@dialloimports.co,+46 70 779 23 27,sweden,connected,Lead,NaN,Marcus Wong,6/11/2026,NaN,"Referred by Xiu Ying Choi, warm intro. Great f...",NaN
11,100234822,Aiko,Goh,Aiko Goh,NaN,Singh Logistics Partners,aiko.g@singhlogistics.biz,+65 8177 3442,singapore,opportunity,Lead,Offline Sources,Grace Osei,2026-06-10T00:00:00Z,6/10/2026,Scanned the QR code at our TechCrunch Disrupt ...,NaN
12,100234823,Wei Chen,Ang,Wei Chen Ang,NaN,Fischer Trading Pte Ltd,weichena@fischertrading.io,+30 694 373 3608,greece,closed won,Other,NaN,Marcus Wong,3/15/2026,2026-05-14,Googled us and ended up on the product tour pa...,44.0
13,100234824,Joon,Nguyen,Joon Nguyen,Operations Lead,Sato and Co,joonn@sato.io,+63 923 710 8119,philippines,connected,Other,NaN,Grace Osei,2026-04-12,2026-06-16T00:00:00Z,"Met her at the Mobile World Congress booth, sc...",88.0
14,100234825,Fatima,Iyer,Fatima Iyer,NaN,Sim Robotics Freight,fatimai@simrobotics.sg,+40 757 667 230,romania,contacted,Opportunity,NaN,Noah Bennett,2025-11-29,NaN,Connected on LinkedIn after commenting on our ...,NaN
15,100234826,Kai,Osei,Kai Osei,Operations Lead,Tanaka Freight,kaio@tanaka.biz,+66 7 6085 4680,thailand,closed won,Marketing Qualified Lead,Other Campaigns,Wei Chen,2025-09-13,NaN,Other - walked into our office without an appo...,NaN
16,100234827,Hassan,Schulz,Hassan Schulz,Founder,Osei Freight Solutions,hassan.s@osei.com.au,+84 98 355 2988,vietnam,qualified,Marketing Qualified Lead,NaN,Hana Kobayashi,5/30/2026,2026-06-18,Googled us and ended up on the product tour pa...,NaN
17,100234828,Nadia,Sun,Nadia Sun,Operations Lead,Bakker Partners,n.sun@bakker.com,+91 77577 60205,india,closed lost,Marketing Qualified Lead,Referrals,Fatima Rahman,10/3/2025,2026-03-21,"Referred by Ismail Reyes, warm intro. Very int...",NaN
18,100234829,Farah,Martins,Farah Martins,Marketing Director,Verma Consulting Partners,f.martins@vermaconsulting.net,+234 804 379 8140,nigeria,qualified,Lead,NaN,Noah Bennett,2026-02-20,2026-06-02T00:00:00Z,Connected on LinkedIn after commenting on our ...,NaN
19,100234830,Ha-eun,Kang,Ha-eun Kang,NaN,Cruz & Partners Holdings,ha-eun.k@cruzpartners.net,+49 174 8072684,germany,connected,NaN,Social Media,Marcus Wong,2026-04-29,NaN,Linkedin dm inbound asking about pricing.,NaN
20,100234831,Lucas,Bruno,Lucas Bruno,Marketing Director,Huang Analytics Robotics,l.bruno@huanganalytics.co,+81 75-6096-2771,japan,opportunity,Lead,Offline Sources,Diego Alvarez,2026-03-12,2026-06-11,"Met at the booth during Mobile World Congress,...",NaN
21,100234832,Farah,Bruno,Farah Bruno,NaN,Huang Analytics Robotics,farah.bruno@huanganalytics.co,+91 84270 33086,india,closed lost,Customer,NaN,Diego Alvarez,6/3/2026,2026-06-17,Saw our post about replacing hubspot and comme...,NaN
22,100234833,Antoine,Asante,Antoine Asante,Founder,Koh & Sons Co.,antoinea@kohsons.co,+39 357 710 5526,italy,opportunity,Lead,Other Campaigns,Rohan Mehta,2025-12-07,2025-12-07,Manual - added after inbound phone call. Not i...,NaN
23,100234834,Joon,Diallo,Joon Diallo,VP Sales,Huang Analytics and Co,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,6/7/2026,Spoke with them at our Dubai FinTech Week boot...,NaN
24,100234835,NaN,NaN,J. Diallo,VP Sales,Huang Analytics and Pte. Ltd.,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,2026-06-07,Spoke with them at our Dubai FinTech Week boot...,NaN

In [26]:
df_titik = df[df['Full Name'].str.contains('.', regex=False, na=False)]
df_titik['Full Name'].unique()

array(['J. Diallo', 'T. Aina', 'J. Ferrari', 'J. Yoon', 'L. Rao',
       'I. Tanaka', 'C. Christensen', 'D. Ferrari', 'A. Nielsen',
       'O. Ang', 'R. Wagner', 'A. Larsen', 'T. Tanaka', 'S. Iyer',
       'E. Colombo', 'S. Ocampo', 'K. Ricci', 'F. Hansen', 'L. Al-Sayed',
       'A. Becker', 'A. Schmidt', 'Z. Kapoor', 'R. Sorensen', 'S. Bakar',
       'M. Toure', 'Y. Adjei', 'S. Mehta', 'P. Christensen', 'A. Sun',
       'H. Bakker', 'M. Ng', 'R. Ang', 'A. Sow', 'T. Sato', 'S. Jung',
       'S. Nielsen', 'J. Chua', 'O. Sorensen', 'R. Santos', 'A. Pedersen',
       'Z. Ong', 'R. Tanaka', 'L. Wagner', 'K. Toure', 'S. Kowalski',
       'F. Osei', 'A. Dubois', 'M. Chua', 'S. Xu', 'A. Carvalho',
       'M. Ang'], dtype=object)

In [27]:
mask = df['Full Name'].str.contains('.', regex=False, na=False)
idx_list = df[mask].index.tolist()

for idx in idx_list:
    if idx == 0:
        print(f"Index {idx}: tidak punya baris sebelumnya, dilewati.")
        continue
    
    first_name_prev = None
    search_idx = idx - 1
    
    while search_idx >= 0:
        candidate = df.loc[search_idx, 'First Name']
        if pd.notna(candidate):
            first_name_prev = str(candidate)
            break
        search_idx -= 1 
    
    if first_name_prev is None:
        print(f"Index {idx}: tidak ada First Name valid di atasnya, dilewati.")
        continue
    
    full_name_current = df.loc[idx, 'Full Name']
    inisial = full_name_current.split('.')[0].strip() + '.'
    
    full_name_baru = full_name_current.replace(inisial, first_name_prev)
    df.loc[idx, 'Full Name'] = full_name_baru
    
    print(f"Index {idx}: '{full_name_current}' = '{full_name_baru}'")

print(df['Full Name'])

Index 24: 'J. Diallo' = 'Joon Diallo'
Index 111: 'T. Aina' = 'Tunde Aina'
Index 122: 'J. Ferrari' = 'Jia Hui Ferrari'
Index 145: 'J. Yoon' = 'Ji-woo Yoon'
Index 146: 'J. Yoon' = 'Ji-woo Yoon'
Index 156: 'L. Rao' = 'Linh Rao'
Index 157: 'L. Rao' = 'Linh Rao'
Index 185: 'I. Tanaka' = 'Ines Tanaka'
Index 207: 'C. Christensen' = 'Camille Christensen'
Index 276: 'D. Ferrari' = 'Diego Ferrari'
Index 279: 'A. Nielsen' = 'Adaeze Nielsen'
Index 319: 'O. Ang' = 'Omar Ang'
Index 383: 'R. Wagner' = 'Ryan Wagner'
Index 435: 'A. Larsen' = 'Aiko Larsen'
Index 541: 'T. Tanaka' = 'Tunde Tanaka'
Index 584: 'S. Iyer' = 'Sara Iyer'
Index 684: 'E. Colombo' = 'Elijah Colombo'
Index 777: 'S. Ocampo' = 'Siti Ocampo'
Index 828: 'K. Ricci' = 'Kai Ricci'
Index 935: 'F. Hansen' = 'Freya Hansen'
Index 944: 'L. Al-Sayed' = 'Laura Al-Sayed'
Index 947: 'A. Becker' = 'Astrid Becker'
Index 983: 'A. Schmidt' = 'Ahmed Schmidt'
Index 1040: 'Z. Kapoor' = 'Zara Kapoor'
Index 1088: 'R. Sorensen' = 'Rui Sorensen'
Index 1112: 'S. Bakar' = 'Sarah Bakar'
Index 1116: 'M. Toure' = 'Mateo Toure'
Index 1172: 'Y. Adjei' = 'Yuki Adjei'
Index 1227: 'S. Mehta' = 'Sanjay Mehta'
Index 1239: 'P. Christensen' = 'Pedro Christensen'
Index 1269: 'A. Sun' = 'Amina Sun'
Index 1274: 'H. Bakker' = 'Haruto Bakker'
Index 1284: 'M. Ng' = 'Min-jun Ng'
Index 1317: 'R. Ang' = 'Ravi Ang'
Index 1319: 'A. Sow' = 'Adaeze Sow'
Index 1353: 'T. Sato' = 'Tariq Sato'
Index 1388: 'S. Jung' = 'Sarah Jung'
Index 1393: 'S. Nielsen' = 'Sven Nielsen'
Index 1421: 'J. Chua' = 'Jun Wei Chua'
Index 1423: 'O. Sorensen' = 'Oluwaseun Sorensen'
Index 1469: 'R. Santos' = 'Rin Santos'
Index 1528: 'A. Pedersen' = 'Astrid Pedersen'
Index 1569: 'Z. Ong' = 'Zainab Ong'
Index 1581: 'R. Tanaka' = 'Rania Tanaka'
Index 1622: 'L. Wagner' = 'Luca Wagner'
Index 1673: 'K. Toure' = 'Kwame Toure'
Index 1732: 'S. Kowalski' = 'Salma Kowalski'
Index 1736: 'F. Osei' = 'Francesca Osei'
Index 1888: 'A. Dubois' = 'Adam Dubois'
Index 1894: 'M. Chua' = 'Michael Chua'
Index 1926: 'S. Xu' = 'Sara Xu'
Index 1941: 'A. Carvalho' = 'Aiko Carvalho'
Index 1982: 'M. Ang' = 'Mateo Ang'
0               Yuki Aina
1          Wei Ming Malik
2                Linh Lim
3                 Ines Wu
4       Xiu Ying Martinez
              ...
2044            Karim Yap
2045            Karim Yap
2046             Musa Seo
2047             Musa Seo
2048        Valentina Lim
Name: Full Name, Length: 2049, dtype: object

In [28]:
df.iloc[0:25]

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,Lead Status,Lifecycle Stage,Original Source,Contact Owner,Create Date,Last Modified Date,Notes,Lead Score
0,100234811,Yuki,Aina,Yuki Aina,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,china,new,Lead,NaN,Marcus Wong,12/21/2025,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN
1,100234812,Wei Ming,Malik,Wei Ming Malik,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,france,qualified,Lead,Referrals,Rohan Mehta,1/29/2026,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN
2,100234813,Linh,Lim,Linh Lim,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,poland,opportunity,Marketing Qualified Lead,NaN,Grace Osei,2025-09-29,10/15/2025,Filled out the form on the contact page.,NaN
3,100234814,Ines,Wu,Ines Wu,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,portugal,qualified,Lead,Direct Traffic,Priya Nair,2025-10-27T00:00:00Z,2025-12-06,Filled out the form on the contact page. Very ...,NaN
4,100234815,Xiu Ying,Martinez,Xiu Ying Martinez,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,france,closed won,Other,Paid Search,Diego Alvarez,2026-05-18,5/27/2026,Booked a demo via the book-a-demo page after c...,NaN
5,100234816,Natasha,Osei,Natasha Osei,Finance Manager,Singh Logistics Ltd,n.osei@singhlogistics.net,+82 10-8787-3705,south korea,connected,Customer,NaN,Elena Popescu,2026-04-05,2026-06-13,Filled out the form on the blog post on lead s...,NaN
6,100234817,Arjun,Oh,Arjun Oh,Founder,Mekong Pte. Ltd.,arjuno@mekong.net,+62 875-4899-5562,indonesia,closed lost,Opportunity,Other Campaigns,Fatima Rahman,2026-06-04,6/4/2026,Other - reached out via our general info@ inbo...,NaN
7,100234818,Omar,Reyes,Omar Reyes,VP Sales,Sayed Trading Holdings,omar.reyes@sayedtrading.net,+44 7798 299448,united kingdom,opportunity,Opportunity,Organic Search,Wei Chen,2026-04-05,2026-06-03,Googled us and ended up on the book-a-demo pag...,NaN
8,100234819,Abena,Lee,Abena Lee,NaN,Lindqvist AB and Co,abena.l@lindqvistab.net,+31 6 7930 8973,netherlands,contacted,Marketing Qualified Lead,NaN,Diego Alvarez,2025-12-21T00:00:00Z,NaN,Manually added by sales after a phone call fro...,NaN
9,100234820,Nadia,Weber,Nadia Weber,NaN,Sato Labs,nadia.weber@sato.io,+66 9 9565 6183,thailand,connected,Marketing Qualified Lead,NaN,Grace Osei,2026-01-01,2026-02-03T00:00:00Z,Manual - added after inbound phone call. No re...,92.0
10,100234821,Marcus,Russo,Marcus Russo,Founder,Diallo Imports Freight Solutions,marcus.russo@dialloimports.co,+46 70 779 23 27,sweden,connected,Lead,NaN,Marcus Wong,6/11/2026,NaN,"Referred by Xiu Ying Choi, warm intro. Great f...",NaN
11,100234822,Aiko,Goh,Aiko Goh,NaN,Singh Logistics Partners,aiko.g@singhlogistics.biz,+65 8177 3442,singapore,opportunity,Lead,Offline Sources,Grace Osei,2026-06-10T00:00:00Z,6/10/2026,Scanned the QR code at our TechCrunch Disrupt ...,NaN
12,100234823,Wei Chen,Ang,Wei Chen Ang,NaN,Fischer Trading Pte Ltd,weichena@fischertrading.io,+30 694 373 3608,greece,closed won,Other,NaN,Marcus Wong,3/15/2026,2026-05-14,Googled us and ended up on the product tour pa...,44.0
13,100234824,Joon,Nguyen,Joon Nguyen,Operations Lead,Sato and Co,joonn@sato.io,+63 923 710 8119,philippines,connected,Other,NaN,Grace Osei,2026-04-12,2026-06-16T00:00:00Z,"Met her at the Mobile World Congress booth, sc...",88.0
14,100234825,Fatima,Iyer,Fatima Iyer,NaN,Sim Robotics Freight,fatimai@simrobotics.sg,+40 757 667 230,romania,contacted,Opportunity,NaN,Noah Bennett,2025-11-29,NaN,Connected on LinkedIn after commenting on our ...,NaN
15,100234826,Kai,Osei,Kai Osei,Operations Lead,Tanaka Freight,kaio@tanaka.biz,+66 7 6085 4680,thailand,closed won,Marketing Qualified Lead,Other Campaigns,Wei Chen,2025-09-13,NaN,Other - walked into our office without an appo...,NaN
16,100234827,Hassan,Schulz,Hassan Schulz,Founder,Osei Freight Solutions,hassan.s@osei.com.au,+84 98 355 2988,vietnam,qualified,Marketing Qualified Lead,NaN,Hana Kobayashi,5/30/2026,2026-06-18,Googled us and ended up on the product tour pa...,NaN
17,100234828,Nadia,Sun,Nadia Sun,Operations Lead,Bakker Partners,n.sun@bakker.com,+91 77577 60205,india,closed lost,Marketing Qualified Lead,Referrals,Fatima Rahman,10/3/2025,2026-03-21,"Referred by Ismail Reyes, warm intro. Very int...",NaN
18,100234829,Farah,Martins,Farah Martins,Marketing Director,Verma Consulting Partners,f.martins@vermaconsulting.net,+234 804 379 8140,nigeria,qualified,Lead,NaN,Noah Bennett,2026-02-20,2026-06-02T00:00:00Z,Connected on LinkedIn after commenting on our ...,NaN
19,100234830,Ha-eun,Kang,Ha-eun Kang,NaN,Cruz & Partners Holdings,ha-eun.k@cruzpartners.net,+49 174 8072684,germany,connected,NaN,Social Media,Marcus Wong,2026-04-29,NaN,Linkedin dm inbound asking about pricing.,NaN
20,100234831,Lucas,Bruno,Lucas Bruno,Marketing Director,Huang Analytics Robotics,l.bruno@huanganalytics.co,+81 75-6096-2771,japan,opportunity,Lead,Offline Sources,Diego Alvarez,2026-03-12,2026-06-11,"Met at the booth during Mobile World Congress,...",NaN
21,100234832,Farah,Bruno,Farah Bruno,NaN,Huang Analytics Robotics,farah.bruno@huanganalytics.co,+91 84270 33086,india,closed lost,Customer,NaN,Diego Alvarez,6/3/2026,2026-06-17,Saw our post about replacing hubspot and comme...,NaN
22,100234833,Antoine,Asante,Antoine Asante,Founder,Koh & Sons Co.,antoinea@kohsons.co,+39 357 710 5526,italy,opportunity,Lead,Other Campaigns,Rohan Mehta,2025-12-07,2025-12-07,Manual - added after inbound phone call. Not i...,NaN
23,100234834,Joon,Diallo,Joon Diallo,VP Sales,Huang Analytics and Co,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,6/7/2026,Spoke with them at our Dubai FinTech Week boot...,NaN
24,100234835,NaN,NaN,Joon Diallo,VP Sales,Huang Analytics and Pte. Ltd.,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,2026-06-07,Spoke with them at our Dubai FinTech Week boot...,NaN

In [29]:
df.to_csv('data_clean.csv',index=False)

In [30]:
import pandas as pd

df = pd.read_csv("data_clean.csv")

def standarisasi_tanggal(kolom):
    hasil = pd.Series([pd.NaT] * len(kolom), index=kolom.index)

    # Format 1: MM/DD/YYYY 
    fmt1 = pd.to_datetime(kolom, format='%m/%d/%Y', errors='coerce')
    hasil = hasil.where(fmt1.isna(), fmt1)

    # Format 2: YYYY-MM-DD 
    fmt2 = pd.to_datetime(kolom, format='%Y-%m-%d', errors='coerce')
    hasil = hasil.where(~hasil.isna() | fmt2.isna(), fmt2)

    # Format 3: YYYY-MM-DDTHH:MM:SSZ
    fmt3 = pd.to_datetime(kolom, format='%Y-%m-%dT%H:%M:%SZ', errors='coerce')
    hasil = hasil.where(~hasil.isna() | fmt3.isna(), fmt3)

    # Konversi ke format YYYY-MM-DD
    return hasil.dt.strftime('%Y-%m-%d')

df['Create Date']        = standarisasi_tanggal(df['Create Date'])
df['Last Modified Date'] = standarisasi_tanggal(df['Last Modified Date'])

print(df[['Create Date', 'Last Modified Date']].head(10))
print(f"\nCreate Date NaT    : {df['Create Date'].isna().sum()}")
print(f"Last Modified NaT  : {df['Last Modified Date'].isna().sum()}")

  Create Date Last Modified Date
0  2025-12-21         2026-05-24
1  2026-01-29                NaN
2  2025-09-29         2025-10-15
3  2025-10-27         2025-12-06
4  2026-05-18         2026-05-27
5  2026-04-05         2026-06-13
6  2026-06-04         2026-06-04
7  2026-04-05         2026-06-03
8  2025-12-21                NaN
9  2026-01-01         2026-02-03

Create Date NaT    : 0
Last Modified NaT  : 553

In [31]:
df.iloc[0:25]

,Record ID,First Name,Last Name,Full Name,Job Title,Company Name,Email,Phone Number,Country/Region,Lead Status,Lifecycle Stage,Original Source,Contact Owner,Create Date,Last Modified Date,Notes,Lead Score
0,100234811,Yuki,Aina,Yuki Aina,Operations Lead,Singh Logistics & Co,y.aina@singhlogistics.io,+86 138 2424 7912,china,new,Lead,NaN,Marcus Wong,2025-12-21,2026-05-24,He scanned our QR code at the SaaStr Annual bo...,NaN
1,100234812,Wei Ming,Malik,Wei Ming Malik,NaN,Delta Inc,weimingm@delta.co,+33 6 15 68 78 25,france,qualified,Lead,Referrals,Rohan Mehta,2026-01-29,NaN,"Referred by Michael Zhang, warm intro. Connect...",NaN
2,100234813,Linh,Lim,Linh Lim,NaN,Chua Textiles & Co,linh.l@chuatextiles.io,+48 569 755 804,poland,opportunity,Marketing Qualified Lead,NaN,Grace Osei,2025-09-29,2025-10-15,Filled out the form on the contact page.,NaN
3,100234814,Ines,Wu,Ines Wu,Operations Lead,Verma Consulting Trading Co,ines.w@vermaconsulting.com.au,+351 92 241 9348,portugal,qualified,Lead,Direct Traffic,Priya Nair,2025-10-27,2025-12-06,Filled out the form on the contact page. Very ...,NaN
4,100234815,Xiu Ying,Martinez,Xiu Ying Martinez,VP Sales,Martinez Co,xiuying.martinez@martinez.sg,+33 6 74 32 74 23,france,closed won,Other,Paid Search,Diego Alvarez,2026-05-18,2026-05-27,Booked a demo via the book-a-demo page after c...,NaN
5,100234816,Natasha,Osei,Natasha Osei,Finance Manager,Singh Logistics Ltd,n.osei@singhlogistics.net,+82 10-8787-3705,south korea,connected,Customer,NaN,Elena Popescu,2026-04-05,2026-06-13,Filled out the form on the blog post on lead s...,NaN
6,100234817,Arjun,Oh,Arjun Oh,Founder,Mekong Pte. Ltd.,arjuno@mekong.net,+62 875-4899-5562,indonesia,closed lost,Opportunity,Other Campaigns,Fatima Rahman,2026-06-04,2026-06-04,Other - reached out via our general info@ inbo...,NaN
7,100234818,Omar,Reyes,Omar Reyes,VP Sales,Sayed Trading Holdings,omar.reyes@sayedtrading.net,+44 7798 299448,united kingdom,opportunity,Opportunity,Organic Search,Wei Chen,2026-04-05,2026-06-03,Googled us and ended up on the book-a-demo pag...,NaN
8,100234819,Abena,Lee,Abena Lee,NaN,Lindqvist AB and Co,abena.l@lindqvistab.net,+31 6 7930 8973,netherlands,contacted,Marketing Qualified Lead,NaN,Diego Alvarez,2025-12-21,NaN,Manually added by sales after a phone call fro...,NaN
9,100234820,Nadia,Weber,Nadia Weber,NaN,Sato Labs,nadia.weber@sato.io,+66 9 9565 6183,thailand,connected,Marketing Qualified Lead,NaN,Grace Osei,2026-01-01,2026-02-03,Manual - added after inbound phone call. No re...,92.0
10,100234821,Marcus,Russo,Marcus Russo,Founder,Diallo Imports Freight Solutions,marcus.russo@dialloimports.co,+46 70 779 23 27,sweden,connected,Lead,NaN,Marcus Wong,2026-06-11,NaN,"Referred by Xiu Ying Choi, warm intro. Great f...",NaN
11,100234822,Aiko,Goh,Aiko Goh,NaN,Singh Logistics Partners,aiko.g@singhlogistics.biz,+65 8177 3442,singapore,opportunity,Lead,Offline Sources,Grace Osei,2026-06-10,2026-06-10,Scanned the QR code at our TechCrunch Disrupt ...,NaN
12,100234823,Wei Chen,Ang,Wei Chen Ang,NaN,Fischer Trading Pte Ltd,weichena@fischertrading.io,+30 694 373 3608,greece,closed won,Other,NaN,Marcus Wong,2026-03-15,2026-05-14,Googled us and ended up on the product tour pa...,44.0
13,100234824,Joon,Nguyen,Joon Nguyen,Operations Lead,Sato and Co,joonn@sato.io,+63 923 710 8119,philippines,connected,Other,NaN,Grace Osei,2026-04-12,2026-06-16,"Met her at the Mobile World Congress booth, sc...",88.0
14,100234825,Fatima,Iyer,Fatima Iyer,NaN,Sim Robotics Freight,fatimai@simrobotics.sg,+40 757 667 230,romania,contacted,Opportunity,NaN,Noah Bennett,2025-11-29,NaN,Connected on LinkedIn after commenting on our ...,NaN
15,100234826,Kai,Osei,Kai Osei,Operations Lead,Tanaka Freight,kaio@tanaka.biz,+66 7 6085 4680,thailand,closed won,Marketing Qualified Lead,Other Campaigns,Wei Chen,2025-09-13,NaN,Other - walked into our office without an appo...,NaN
16,100234827,Hassan,Schulz,Hassan Schulz,Founder,Osei Freight Solutions,hassan.s@osei.com.au,+84 98 355 2988,vietnam,qualified,Marketing Qualified Lead,NaN,Hana Kobayashi,2026-05-30,2026-06-18,Googled us and ended up on the product tour pa...,NaN
17,100234828,Nadia,Sun,Nadia Sun,Operations Lead,Bakker Partners,n.sun@bakker.com,+91 77577 60205,india,closed lost,Marketing Qualified Lead,Referrals,Fatima Rahman,2025-10-03,2026-03-21,"Referred by Ismail Reyes, warm intro. Very int...",NaN
18,100234829,Farah,Martins,Farah Martins,Marketing Director,Verma Consulting Partners,f.martins@vermaconsulting.net,+234 804 379 8140,nigeria,qualified,Lead,NaN,Noah Bennett,2026-02-20,2026-06-02,Connected on LinkedIn after commenting on our ...,NaN
19,100234830,Ha-eun,Kang,Ha-eun Kang,NaN,Cruz & Partners Holdings,ha-eun.k@cruzpartners.net,+49 174 8072684,germany,connected,NaN,Social Media,Marcus Wong,2026-04-29,NaN,Linkedin dm inbound asking about pricing.,NaN
20,100234831,Lucas,Bruno,Lucas Bruno,Marketing Director,Huang Analytics Robotics,l.bruno@huanganalytics.co,+81 75-6096-2771,japan,opportunity,Lead,Offline Sources,Diego Alvarez,2026-03-12,2026-06-11,"Met at the booth during Mobile World Congress,...",NaN
21,100234832,Farah,Bruno,Farah Bruno,NaN,Huang Analytics Robotics,farah.bruno@huanganalytics.co,+91 84270 33086,india,closed lost,Customer,NaN,Diego Alvarez,2026-06-03,2026-06-17,Saw our post about replacing hubspot and comme...,NaN
22,100234833,Antoine,Asante,Antoine Asante,Founder,Koh & Sons Co.,antoinea@kohsons.co,+39 357 710 5526,italy,opportunity,Lead,Other Campaigns,Rohan Mehta,2025-12-07,2025-12-07,Manual - added after inbound phone call. Not i...,NaN
23,100234834,Joon,Diallo,Joon Diallo,VP Sales,Huang Analytics and Co,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,2026-06-07,Spoke with them at our Dubai FinTech Week boot...,NaN
24,100234835,NaN,NaN,Joon Diallo,VP Sales,Huang Analytics and Pte. Ltd.,joond@huanganalytics.co,+1 323 555 0192,united states,contacted,Sales Qualified Lead,NaN,Marcus Wong,2026-06-02,2026-06-07,Spoke with them at our Dubai FinTech Week boot...,NaN

In [32]:
df.to_csv('data_clean.csv',index=False)

In [33]:
df['Original Source'].unique()

array([nan, 'Referrals', 'Direct Traffic', 'Paid Search',
       'Other Campaigns', 'Organic Search', 'Offline Sources',
       'Social Media'], dtype=object)

In [34]:
df['Lead Status'].unique()

array(['new', 'qualified', 'opportunity', 'closed won', 'connected',
       'closed lost', 'contacted'], dtype=object)